#!/usr/bin/env python3
"""Patch the buildozer.spec generated by pyside6-android-deploy.

The Qt deploy tool only writes Qt-specific settings into the buildozer.spec it
generates and then deletes it again at the end of its run.  It also hardcodes
``p4a.branch = develop``.  Cloning python-for-android ``develop`` today builds
CPython 3.14, while the PySide6 6.8 Android wheels are cp311 binaries - the
resulting APK ships a Python that cannot load PySide6, so the app closes
immediately after launch.

This script:
  * pins python-for-android to a release that builds Python 3.11 (matching the
    PySide6 6.8 cp311 Android wheels) while still containing the Qt bootstrap,
  * restores the SMS permissions and the MalinoSmsReceiver Java sources that
    the generated spec does not carry over from the project.
"""

import argparse
from pathlib import Path

SMS_PERMISSIONS = [
    "RECEIVE_SMS",
    "READ_SMS",
    "POST_NOTIFICATIONS",
]


def read_value(text: str, key: str, default: str = "") -> str:
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith(f"{key} ") or stripped.startswith(f"{key}="):
            _, _, value = stripped.partition("=")
            return value.strip()
    return default


def set_value(text: str, section: str, key: str, value: str) -> str:
    """Set ``key = value`` inside ``[section]`` (uncommented, replaced)."""
    lines = text.splitlines()
    in_section = False
    replaced = False
    out = []
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("[") and stripped.endswith("]"):
            if in_section and not replaced:
                out.append(f"{key} = {value}")
                replaced = True
            in_section = stripped == f"[{section}]"
        if in_section and (stripped == key or stripped.startswith(f"{key} ")
                           or stripped.startswith(f"{key}=") or stripped == f"# {key}"
                           or stripped.startswith(f"# {key} ")):
            if not replaced:
                out.append(f"{key} = {value}")
                replaced = True
            continue
        out.append(line)
    if not replaced:
        if in_section:
            out.append(f"{key} = {value}")
        else:
            out.append(f"[{section}]")
            out.append(f"{key} = {value}")
    return "\n".join(out) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("spec", type=Path)
    parser.add_argument("--p4a-ref", default="v2024.01.21",
                        help="python-for-android branch/tag to pin")
    args = parser.parse_args()

    text = args.spec.read_text(encoding="utf-8")

    # 1. Pin python-for-android to a python-3.11 release with the qt bootstrap.
    text = set_value(text, "app", "p4a.branch", args.p4a_ref)

    # 2. SMS permissions (the generated spec only carries wheel-derived ones).
    current = [p.strip() for p in read_value(text, "android.permissions").split(",") if p.strip()]
    merged = list(dict.fromkeys(current + SMS_PERMISSIONS))
    text = set_value(text, "app", "android.permissions", ", ".join(merged))

    # 3. Java sources for the SMS receiver (buildozer passes --add-source to p4a).
    text = set_value(text, "app", "android.add_src", "android/src")

    # 4. Hook that injects the receiver into the rendered AndroidManifest.
    hook_path = Path(__file__).resolve().parent / "p4a" / "hook.py"
    text = set_value(text, "app", "p4a.hook", str(hook_path))

    # 6. Sensible SDK levels for the Qt wheels (min SDK 26 = Android 8).
    text = set_value(text, "app", "android.minapi", "26")
    text = set_value(text, "app", "android.api", "34")
    text = set_value(text, "app", "orientation", "portrait")

    args.spec.write_text(text, encoding="utf-8")
    print(f"[patch] {args.spec} patched (p4a={args.p4a_ref}, sms permissions + receiver)")


if __name__ == "__main__":
    main()
