package ir.kharjyar.app.ui.screens

import android.Manifest
import android.content.pm.PackageManager
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Add
import androidx.compose.material.icons.filled.ArrowBack
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.unit.dp
import androidx.core.content.ContextCompat
import com.google.mlkit.vision.common.InputImage
import com.google.mlkit.vision.text.TextRecognition
import com.google.mlkit.vision.text.latin.TextRecognizerOptions
import ir.kharjyar.app.core.date.PersianDate
import ir.kharjyar.app.core.money.Money
import ir.kharjyar.app.core.text.Digits
import ir.kharjyar.app.data.db.*
import ir.kharjyar.app.ui.AppViewModel
import ir.kharjyar.app.ui.components.AmountTextField
import ir.kharjyar.app.ui.components.PersianDateField
import kotlinx.coroutines.launch
import java.io.File

@Composable fun ChecksScreen(vm:AppViewModel){val checks by vm.checks.collectAsState();val settings by vm.settings.collectAsState();val scope=rememberCoroutineScope();var entryDirection by remember{mutableStateOf<Int?>(null)};var showChooser by remember{mutableStateOf(false)};var filter by remember{mutableStateOf<Int?>(null)}
 if(entryDirection!=null){CheckEntryPage(vm,entryDirection!!,{entryDirection=null},{entryDirection=null});return}
 val shown=checks.filter{filter==null||it.direction==filter};Box(Modifier.fillMaxSize()){Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(start=16.dp,end=16.dp,top=12.dp,bottom=92.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){Text("مدیریت چک‌ها",style=MaterialTheme.typography.headlineSmall);Row(horizontalArrangement=Arrangement.spacedBy(6.dp)){FilterChip(filter==null,{filter=null},{Text("همه")});FilterChip(filter==CheckDirection.RECEIVED,{filter=CheckDirection.RECEIVED},{Text("دریافتی")});FilterChip(filter==CheckDirection.ISSUED,{filter=CheckDirection.ISSUED},{Text("صادرشده")})};if(shown.isEmpty())Text("هنوز چکی ثبت نشده است.",modifier=Modifier.padding(vertical=24.dp));shown.forEach{c->val received=c.direction==CheckDirection.RECEIVED;val accent=if(received)Color(0xFF20A565) else Color(0xFFE14B55);Card(colors=CardDefaults.cardColors(containerColor=accent.copy(alpha=.10f)),modifier=Modifier.fillMaxWidth().border(1.4.dp,accent,RoundedCornerShape(16.dp))){Column(Modifier.padding(14.dp),verticalArrangement=Arrangement.spacedBy(5.dp)){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text(c.counterparty,style=MaterialTheme.typography.titleMedium);Text(if(received)"چک دریافتی" else "چک صادرشده",color=accent,style=MaterialTheme.typography.labelLarge)};Text(Money.format(c.amountRial,settings.moneyUnit),style=MaterialTheme.typography.titleMedium,color=accent);Text("سررسید: ${PersianDate.fromMillis(c.dueAt).format()}");if(c.bankName.isNotBlank())Text("بانک: ${c.bankName}");if(c.sayadId.isNotBlank())Text("شناسه صیادی: ${c.sayadId}");if(c.serialNumber.isNotBlank())Text("سریال: ${c.serialNumber}");Text(when(c.status){CheckStatus.CLEARED->"وصول/پاس‌شده";CheckStatus.BOUNCED->"برگشت‌خورده";CheckStatus.CANCELLED->"لغوشده";else->"در انتظار"},color=accent);if(c.status==CheckStatus.PENDING)Row{TextButton({scope.launch{vm.repo.db.checkDao().update(c.copy(status=CheckStatus.CLEARED))}}){Text("وصول/پاس شد")};TextButton({scope.launch{vm.repo.db.checkDao().update(c.copy(status=CheckStatus.BOUNCED))}}){Text("برگشت خورد",color=MaterialTheme.colorScheme.error)}}}}}}
  FloatingActionButton({showChooser=true},Modifier.align(Alignment.BottomEnd).padding(20.dp),containerColor=MaterialTheme.colorScheme.primary){Icon(Icons.Filled.Add,"افزودن چک")}}
 if(showChooser)AlertDialog(onDismissRequest={showChooser=false},title={Text("نوع چک را انتخاب کنید")},text={Column(verticalArrangement=Arrangement.spacedBy(10.dp)){Button({showChooser=false;entryDirection=CheckDirection.RECEIVED},Modifier.fillMaxWidth(),colors=ButtonDefaults.buttonColors(containerColor=Color(0xFF1B8F52))){Text("ثبت چک دریافت‌شده")};Button({showChooser=false;entryDirection=CheckDirection.ISSUED},Modifier.fillMaxWidth(),colors=ButtonDefaults.buttonColors(containerColor=Color(0xFFD33B45))){Text("ثبت چک صادرشده")}}},confirmButton={})
}

@Composable private fun CheckEntryPage(vm:AppViewModel,direction:Int,onDone:()->Unit,onCancel:()->Unit){val scope=rememberCoroutineScope();val context=LocalContext.current;val received=direction==CheckDirection.RECEIVED;var issuer by remember{mutableStateOf("")};var receiver by remember{mutableStateOf("")};var nationalId by remember{mutableStateOf("")};var chequeAccount by remember{mutableStateOf("")};var chequeIban by remember{mutableStateOf("")};var amountWords by remember{mutableStateOf("")};var amount by remember{mutableStateOf("")};var party by remember{mutableStateOf("")};var bank by remember{mutableStateOf("")};var sayad by remember{mutableStateOf("")};var serial by remember{mutableStateOf("")};var due by remember{mutableStateOf(PersianDate.today())};var imagePath by remember{mutableStateOf("")};var cameraUri by remember{mutableStateOf<android.net.Uri?>(null)};var cameraError by remember{mutableStateOf(false)}
 fun analyze(uri:android.net.Uri){val dir=File(context.filesDir,"checks").apply{mkdirs()};val file=File(dir,"${System.currentTimeMillis()}.jpg");context.contentResolver.openInputStream(uri)?.use{input->file.outputStream().use{input.copyTo(it)}};imagePath=file.absolutePath;TextRecognition.getClient(TextRecognizerOptions.DEFAULT_OPTIONS).process(InputImage.fromFilePath(context,uri)).addOnSuccessListener{result->val p=ir.kharjyar.app.core.check.SayadCheckParser.parse(result.text);if(p.sayadId.isNotBlank())sayad=p.sayadId;if(p.serialNumber.isNotBlank())serial=p.serialNumber;p.amountRial?.let{amount=it.toString()};p.dueDate?.let{due=it};if(p.bankName.isNotBlank())bank=p.bankName;if(p.issuerName.isNotBlank())issuer=p.issuerName;if(p.receiverName.isNotBlank()){receiver=p.receiverName;party=p.receiverName};if(p.nationalId.isNotBlank())nationalId=p.nationalId;if(p.accountNumber.isNotBlank())chequeAccount=p.accountNumber;if(p.iban.isNotBlank())chequeIban=p.iban;if(p.amountWords.isNotBlank())amountWords=p.amountWords}}
 val gallery=rememberLauncherForActivityResult(ActivityResultContracts.GetContent()){it?.let(::analyze)};val camera=rememberLauncherForActivityResult(ActivityResultContracts.TakePicture()){ok->if(ok)cameraUri?.let(::analyze)};fun openCamera(){val f=File(context.cacheDir,"check-camera-${System.currentTimeMillis()}.jpg");val uri=androidx.core.content.FileProvider.getUriForFile(context,"${context.packageName}.files",f);cameraUri=uri;camera.launch(uri)};val permission=rememberLauncherForActivityResult(ActivityResultContracts.RequestPermission()){granted->cameraError=!granted;if(granted)openCamera()}
 val accent=if(received)Color(0xFF1B8F52) else Color(0xFFD33B45);Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(16.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){TextButton(onCancel){Icon(Icons.Filled.ArrowBack,null);Text("بازگشت به فهرست")};Text(if(received)"ثبت چک دریافت‌شده" else "ثبت چک صادرشده",style=MaterialTheme.typography.headlineSmall,color=accent);Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){OutlinedButton({if(ContextCompat.checkSelfPermission(context,Manifest.permission.CAMERA)==PackageManager.PERMISSION_GRANTED)openCamera()else permission.launch(Manifest.permission.CAMERA)},Modifier.weight(1f)){Text("اسکن با دوربین")};OutlinedButton({gallery.launch("image/*")},Modifier.weight(1f)){Text("انتخاب از گالری")}};if(cameraError)Text("اجازه دوربین داده نشده است.",color=MaterialTheme.colorScheme.error);if(imagePath.isNotBlank())Text("تصویر خوانده شد؛ اطلاعات را بررسی کنید.",color=accent);OutlinedTextField(party,{party=it},label={Text("طرف حساب")},modifier=Modifier.fillMaxWidth());OutlinedTextField(issuer,{issuer=it},label={Text("نام صادرکننده")},modifier=Modifier.fillMaxWidth());OutlinedTextField(receiver,{receiver=it;party=it},label={Text("نام دریافت‌کننده")},modifier=Modifier.fillMaxWidth());OutlinedTextField(nationalId,{nationalId=Digits.normalize(it).filter(Char::isDigit)},label={Text("کد/شناسه ملی")},modifier=Modifier.fillMaxWidth());AmountTextField(amount,{amount=it},"مبلغ چک به عدد (ریال)",Modifier.fillMaxWidth());OutlinedTextField(amountWords,{amountWords=it},label={Text("مبلغ چک به حروف")},modifier=Modifier.fillMaxWidth());OutlinedTextField(bank,{bank=it},label={Text("بانک و شعبه")},modifier=Modifier.fillMaxWidth());OutlinedTextField(sayad,{sayad=Digits.normalize(it).filter(Char::isDigit)},label={Text("شناسه ۱۶ رقمی صیادی")},modifier=Modifier.fillMaxWidth());OutlinedTextField(serial,{serial=Digits.normalize(it).filter(Char::isDigit)},label={Text("شماره سریال/سری چک")},modifier=Modifier.fillMaxWidth());OutlinedTextField(chequeAccount,{chequeAccount=Digits.normalize(it)},label={Text("شماره حساب چک")},modifier=Modifier.fillMaxWidth());OutlinedTextField(chequeIban,{chequeIban=it.uppercase()},label={Text("شماره شبا")},modifier=Modifier.fillMaxWidth());Text("تاریخ سررسید");PersianDateField(due,{due=it});Button({scope.launch{vm.repo.db.checkDao().insert(CheckEntity(direction=direction,amountRial=Digits.parseAmount(amount)?:0,counterparty=party,bankName=bank,sayadId=sayad,serialNumber=serial,issuedAt=System.currentTimeMillis(),dueAt=due.startOfDayMillis(),reminderAt=due.startOfDayMillis(),imagePath=imagePath,issuerName=issuer,receiverName=receiver,nationalId=nationalId,chequeAccountNumber=chequeAccount,chequeIban=chequeIban,amountInWords=amountWords));onDone()}},enabled=party.isNotBlank()&&(Digits.parseAmount(amount)?:0)>0,modifier=Modifier.fillMaxWidth(),colors=ButtonDefaults.buttonColors(containerColor=accent)){Text(if(received)"ثبت چک دریافت‌شده و یادآور" else "ثبت چک صادرشده و یادآور")}}
}
