package ir.kharjyar.app.ui.screens

import androidx.activity.compose.BackHandler
import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.horizontalScroll
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Add
import androidx.compose.material.icons.filled.ArrowBack
import androidx.compose.material.icons.filled.Delete
import androidx.compose.material.icons.filled.Edit
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.platform.LocalLayoutDirection
import androidx.compose.ui.unit.LayoutDirection
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import ir.kharjyar.app.core.date.PersianDate
import ir.kharjyar.app.core.money.Money
import ir.kharjyar.app.core.text.Digits
import ir.kharjyar.app.data.db.*
import ir.kharjyar.app.ui.AppViewModel
import ir.kharjyar.app.ui.components.showSavedMessage
import ir.kharjyar.app.ui.components.PersianDateField
import ir.kharjyar.app.work.LifeReminderWorker
import kotlinx.coroutines.launch

private const val VEHICLE_ENTRY=1
private const val SERVICE_ENTRY=2

@Composable fun VehiclesScreen(vm:AppViewModel){val dao=vm.repo.db.civicDao();val vehicles by dao.observeVehicles().collectAsState(initial=emptyList());val people by dao.observePeople().collectAsState(initial=emptyList());val messages by dao.observeMessages().collectAsState(initial=emptyList());val services by dao.observeOilServices().collectAsState(initial=emptyList());val settings by vm.settings.collectAsState();val scope=rememberCoroutineScope();var entry by remember{mutableStateOf<Int?>(null)};var chooser by remember{mutableStateOf(false)};var filter by remember{mutableStateOf<Int?>(null)};var selectedVehicleId by remember{mutableStateOf<Long?>(null)};var editingVehicleId by remember{mutableStateOf<Long?>(null)};var pendingDelete by remember{mutableStateOf<VehicleEntity?>(null)}
 BackHandler(enabled=entry!=null||selectedVehicleId!=null){if(entry!=null){entry=null;editingVehicleId=null}else selectedVehicleId=null}
 if(entry!=null){VehicleEntryPage(vm,entry!!,vehicles.firstOrNull{it.id==editingVehicleId},{entry=null;editingVehicleId=null},{entry=null;editingVehicleId=null});return}
 selectedVehicleId?.let{id->vehicles.firstOrNull{it.id==id}?.let{vehicle->VehiclePlateDetail(vehicle,people,services,messages,settings.moneyUnit,dao,{selectedVehicleId=null});return}}
 fun allFines(v:VehicleEntity):List<CivicMessageEntity> = messages.filter { message ->
  message.kind==CivicMessageKind.TRAFFIC_FINE &&
   (message.vehicleId==v.id || (message.vehicleId==null && ir.kharjyar.app.core.sms.IranianPlateMatcher.matches(message.body,v.plate)))
 }
 fun unreadFines(v:VehicleEntity):List<CivicMessageEntity> = allFines(v).filter{!it.read}
 val shown=vehicles.filter{filter==null||(filter==1&&unreadFines(it).isNotEmpty())||(filter==0&&unreadFines(it).isEmpty())};Box(Modifier.fillMaxSize()){Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(start=16.dp,end=16.dp,top=12.dp,bottom=92.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){Text("وسایل نقلیه",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(8.dp)){VehicleSummary("بدون جریمه جدید",vehicles.count{unreadFines(it).isEmpty()},Color(0xFF1B8F52),Modifier.weight(1f));VehicleSummary("دارای جریمه جدید",vehicles.count{unreadFines(it).isNotEmpty()},Color(0xFFD33B45),Modifier.weight(1f))};Row(horizontalArrangement=Arrangement.spacedBy(6.dp)){FilterChip(filter==null,{filter=null},{Text("همه")});FilterChip(filter==0,{filter=0},{Text("عادی")});FilterChip(filter==1,{filter=1},{Text("جریمه جدید")})};if(shown.isEmpty())Card(Modifier.fillMaxWidth()){Text(if(vehicles.isEmpty())"برای شروع، وسیله نقلیه خود را ثبت کنید." else "وسیله نقلیه‌ای در این فیلتر نیست.",Modifier.padding(24.dp))};shown.forEach{vehicle->
 val fines=unreadFines(vehicle);val totalFineRial=allFines(vehicle).mapNotNull{ir.kharjyar.app.core.sms.TrafficFineParser.amountRial(it.body)}.sum();val accent=if(fines.isEmpty())Color(0xFF20A565) else Color(0xFFE14B55);val ownerName=vehicle.ownerName.ifBlank{vehicle.ownerId?.let{id->people.firstOrNull{it.id==id}?.name}?:"خودم"};val vehicleServices=services.filter{it.vehicleId==vehicle.id};val latest=vehicleServices.maxByOrNull{it.servicedAt}
 Card(colors=CardDefaults.cardColors(containerColor=Color.Transparent),shape=RoundedCornerShape(22.dp),modifier=Modifier.fillMaxWidth().border(1.3.dp,accent.copy(.72f),RoundedCornerShape(22.dp))){
  Column(Modifier.fillMaxWidth().background(Brush.linearGradient(listOf(accent.copy(.16f),MaterialTheme.colorScheme.surface,MaterialTheme.colorScheme.surface))).clickable{selectedVehicleId=vehicle.id}.padding(15.dp),verticalArrangement=Arrangement.spacedBy(9.dp)){
   Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(48.dp).background(accent.copy(.18f),RoundedCornerShape(15.dp)),contentAlignment=Alignment.Center){Text("🚘",style=MaterialTheme.typography.headlineSmall)};Spacer(Modifier.width(10.dp));Column(Modifier.weight(1f)){Text(vehicle.title,style=MaterialTheme.typography.titleMedium,fontWeight=FontWeight.Bold);Text("${vehicle.vehicleType} • مالک: $ownerName",style=MaterialTheme.typography.bodySmall,color=MaterialTheme.colorScheme.onSurfaceVariant)};Surface(color=accent.copy(.14f),shape=RoundedCornerShape(50)){Text(if(fines.isEmpty())"عادی" else "${Digits.toPersian(fines.size.toString())} جریمه جدید",Modifier.padding(horizontal=10.dp,vertical=5.dp),color=accent,fontWeight=FontWeight.Bold,style=MaterialTheme.typography.labelMedium)}}
   VehiclePlateBadge(vehicle.plate)
   if(totalFineRial>0)Text("جمع جرائم: ${Money.format(totalFineRial,settings.moneyUnit)}",color=Color(0xFFE14B55),fontWeight=FontWeight.Bold)
   if(latest!=null){HorizontalDivider();Text("آخرین سرویس در کیلومتر ${Digits.toPersian(latest.currentKm.toString())}");Text("تعویض بعدی: ${Digits.toPersian(latest.nextKm.toString())} کیلومتر • ${PersianDate.fromMillis(latest.nextDueAt).format()}",color=accent)}else Text("سرویس تعویض روغن ثبت نشده است.",style=MaterialTheme.typography.bodySmall,color=MaterialTheme.colorScheme.onSurfaceVariant)
   HorizontalDivider();Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.End){TextButton({editingVehicleId=vehicle.id;entry=VEHICLE_ENTRY}){Icon(Icons.Filled.Edit,null);Spacer(Modifier.width(4.dp));Text("ویرایش")};TextButton({pendingDelete=vehicle}){Icon(Icons.Filled.Delete,null,tint=MaterialTheme.colorScheme.error);Spacer(Modifier.width(4.dp));Text("حذف",color=MaterialTheme.colorScheme.error)}}
  }
 }
}
 }
 FloatingActionButton({chooser=true},Modifier.align(Alignment.BottomEnd).padding(20.dp)){Icon(Icons.Filled.Add,"افزودن")}
 if(chooser)AlertDialog(onDismissRequest={chooser=false},title={Text("چه موردی ثبت شود؟")},text={Column(verticalArrangement=Arrangement.spacedBy(10.dp)){Button({chooser=false;editingVehicleId=null;entry=VEHICLE_ENTRY},Modifier.fillMaxWidth(),border=BorderStroke(1.5.dp,Color(0xFF1B8F52))){Text("وسیله نقلیه جدید")};Button({chooser=false;entry=SERVICE_ENTRY},Modifier.fillMaxWidth(),enabled=vehicles.isNotEmpty(),border=BorderStroke(1.5.dp,Color(0xFFD33B45))){Text("سرویس و تعویض روغن")};if(vehicles.isEmpty())Text("برای ثبت سرویس، ابتدا یک وسیله نقلیه اضافه کنید.",style=MaterialTheme.typography.bodySmall)}},confirmButton={})
 pendingDelete?.let{vehicle->AlertDialog(onDismissRequest={pendingDelete=null},title={Text("حذف وسیله نقلیه؟")},text={Text("«${vehicle.title}» و سوابق سرویس آن حذف می‌شوند. پیامک‌ها و جرائم اصلی حذف نخواهند شد.")},confirmButton={Button({scope.launch{dao.detachVehicleMessages(vehicle.id);dao.deleteVehicleServices(vehicle.id);dao.deleteVehicle(vehicle.id);pendingDelete=null}}){Text("تأیید حذف")}},dismissButton={TextButton({pendingDelete=null}){Text("انصراف")}})}
}
}

@Composable private fun VehiclePlateDetail(vehicle:VehicleEntity,people:List<CoveredPersonEntity>,services:List<VehicleOilServiceEntity>,messages:List<CivicMessageEntity>,unit:ir.kharjyar.app.core.money.MoneyUnit,dao:CivicDao,onBack:()->Unit){
 val scope=rememberCoroutineScope();val ownerName=vehicle.ownerName.ifBlank{vehicle.ownerId?.let{id->people.firstOrNull{it.id==id}?.name}?:"خودم"};val vehicleMessages=messages.filter{it.vehicleId==vehicle.id||(it.vehicleId==null&&ir.kharjyar.app.core.sms.IranianPlateMatcher.matches(it.body,vehicle.plate))};val fines=vehicleMessages.filter{it.kind==CivicMessageKind.TRAFFIC_FINE};val totalFine=fines.mapNotNull{ir.kharjyar.app.core.sms.TrafficFineParser.amountRial(it.body)}.sum();val vehicleServices=services.filter{it.vehicleId==vehicle.id}.sortedByDescending{it.servicedAt}
 Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(16.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){TextButton(onBack){Icon(Icons.Filled.ArrowBack,null);Text("بازگشت به فهرست پلاک‌ها")};Text(vehicle.title,style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);Card(Modifier.fillMaxWidth()){Column(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(5.dp)){Text("پلاک ${vehicle.plate}",style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Bold);Text("نوع: ${vehicle.vehicleType}");Text("مالک: $ownerName");Text("تعداد جرائم: ${Digits.toPersian(fines.size.toString())}");Text("جمع مبلغ جرائم: ${Money.format(totalFine,unit)}",color=Color(0xFFD33B45),fontWeight=FontWeight.Bold)}};Text("جرائم و پیامک‌های این پلاک",style=MaterialTheme.typography.titleMedium);if(vehicleMessages.isEmpty())Text("هنوز پیامکی برای این پلاک ثبت نشده است.");vehicleMessages.sortedByDescending{it.receivedAt}.forEach{m->Card(Modifier.fillMaxWidth()){Column(Modifier.padding(12.dp),verticalArrangement=Arrangement.spacedBy(4.dp)){Text(PersianDate.formatDateTime(m.receivedAt),style=MaterialTheme.typography.labelMedium);Text(m.body);if(!m.read)TextButton({scope.launch{dao.updateMessage(m.copy(read=true,vehicleId=vehicle.id))}}){Text("خواندم")}}}};Text("سوابق سرویس",style=MaterialTheme.typography.titleMedium);if(vehicleServices.isEmpty())Text("هنوز سابقه سرویسی ثبت نشده است.");vehicleServices.forEach{s->Card(Modifier.fillMaxWidth()){Column(Modifier.padding(12.dp)){Text("تاریخ: ${PersianDate.fromMillis(s.servicedAt).format()}");Text("کیلومتر: ${Digits.toPersian(s.currentKm.toString())}");if(s.oilType.isNotBlank())Text("روغن: ${s.oilType}");if(s.note.isNotBlank())Text(s.note)}}}}
}

@Composable private fun VehiclePlateBadge(plate:String){CompositionLocalProvider(LocalLayoutDirection provides LayoutDirection.Ltr){Surface(color=Color(0xFFF8F8F8),shape=RoundedCornerShape(10.dp),border=BorderStroke(1.dp,Color(0xFFB8B8B8)),modifier=Modifier.fillMaxWidth()){Row(verticalAlignment=Alignment.CenterVertically){Box(Modifier.width(32.dp).height(48.dp).background(Color(0xFF17458A),RoundedCornerShape(topStart=10.dp,bottomStart=10.dp)),contentAlignment=Alignment.Center){Text("IR",color=Color.White,fontWeight=FontWeight.Bold,style=MaterialTheme.typography.labelSmall)};Text(Digits.toPersian(plate),Modifier.weight(1f),textAlign=androidx.compose.ui.text.style.TextAlign.Center,color=Color(0xFF151515),fontWeight=FontWeight.Bold,style=MaterialTheme.typography.titleMedium)}}}}

@Composable private fun VehicleSummary(label:String,count:Int,color:Color,modifier:Modifier){Card(modifier,colors=CardDefaults.cardColors(containerColor=color.copy(.10f))){Column(Modifier.fillMaxWidth().padding(12.dp),horizontalAlignment=Alignment.CenterHorizontally){Text(Digits.toPersian(count.toString()),style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold,color=color);Text(label,style=MaterialTheme.typography.labelMedium)}}}

@Composable private fun IranianPlateInput(value:String,onValueChange:(String)->Unit){
 val parsed=remember(value){ir.kharjyar.app.core.sms.IranianPlateMatcher.extract(value)}
 var left by remember(value){mutableStateOf(parsed?.leftTwo.orEmpty())};var letter by remember(value){mutableStateOf(parsed?.letter.orEmpty())};var serial by remember(value){mutableStateOf(parsed?.serialThree.orEmpty())};var iran by remember(value){mutableStateOf(parsed?.iranCode.orEmpty())}
 fun emit(l:String=left,ch:String=letter,s:String=serial,i:String=iran){left=l;letter=ch;serial=s;iran=i;onValueChange("$l$ch${s}ایران$i")}
 val fieldColors=OutlinedTextFieldDefaults.colors(focusedTextColor=Color.Black,unfocusedTextColor=Color.Black,focusedContainerColor=Color.White,unfocusedContainerColor=Color.White,cursorColor=Color.Black,focusedBorderColor=Color(0xFF17458A),unfocusedBorderColor=Color(0xFF777777))
 Column(verticalArrangement=Arrangement.spacedBy(6.dp)){Text("شماره پلاک ایران",style=MaterialTheme.typography.labelLarge);CompositionLocalProvider(LocalLayoutDirection provides LayoutDirection.Ltr){Card(shape=RoundedCornerShape(10.dp),modifier=Modifier.fillMaxWidth(),colors=CardDefaults.cardColors(containerColor=Color(0xFFF4F4F4))){Row(Modifier.fillMaxWidth().padding(6.dp),verticalAlignment=Alignment.CenterVertically,horizontalArrangement=Arrangement.spacedBy(4.dp)){Box(Modifier.width(26.dp).height(58.dp).background(Color(0xFF17458A),RoundedCornerShape(5.dp)),contentAlignment=Alignment.Center){Text("IR",color=Color.White,style=MaterialTheme.typography.labelSmall)};OutlinedTextField(left,{emit(l=Digits.normalize(it).filter(Char::isDigit).take(2))},placeholder={Text("۸۶",color=Color.Gray)},singleLine=true,textStyle=LocalTextStyle.current.copy(color=Color.Black),colors=fieldColors,modifier=Modifier.width(58.dp).height(58.dp));OutlinedTextField(letter,{raw->emit(ch=raw.filter{it in 'آ'..'ی'||it=='♿'}.take(1))},placeholder={Text("س",color=Color.Gray)},singleLine=true,textStyle=LocalTextStyle.current.copy(color=Color.Black),colors=fieldColors,modifier=Modifier.width(49.dp).height(58.dp));OutlinedTextField(serial,{emit(s=Digits.normalize(it).filter(Char::isDigit).take(3))},placeholder={Text("۶۷۳",color=Color.Gray)},singleLine=true,textStyle=LocalTextStyle.current.copy(color=Color.Black),colors=fieldColors,modifier=Modifier.width(76.dp).height(58.dp));OutlinedTextField(iran,{emit(i=Digits.normalize(it).filter(Char::isDigit).take(2))},label={Text("ایران",color=Color.Black)},placeholder={Text("۷۳",color=Color.Gray)},singleLine=true,textStyle=LocalTextStyle.current.copy(color=Color.Black),colors=fieldColors,modifier=Modifier.width(76.dp).height(58.dp))}}};Row(verticalAlignment=Alignment.CenterVertically){Text("برای پلاک ویژه: ",style=MaterialTheme.typography.bodySmall);TextButton({emit(ch="♿")}){Text("نماد معلولین ♿")};if(letter=="♿")TextButton({emit(ch="")}){Text("حرف معمولی")}}}
}

@Composable private fun MotorcyclePlateInput(value:String,onValueChange:(String)->Unit){
 val normalized=Digits.normalize(value).filter(Char::isDigit).take(8);var top by remember(value){mutableStateOf(normalized.take(3))};var bottom by remember(value){mutableStateOf(normalized.drop(3).take(5))}
 fun emit(t:String=top,b:String=bottom){top=t;bottom=b;onValueChange("موتور$t/$b")}
 val colors=OutlinedTextFieldDefaults.colors(focusedTextColor=Color.Black,unfocusedTextColor=Color.Black,focusedContainerColor=Color.White,unfocusedContainerColor=Color.White,cursorColor=Color.Black,focusedBorderColor=Color(0xFF17458A),unfocusedBorderColor=Color(0xFF777777))
 Column(verticalArrangement=Arrangement.spacedBy(6.dp)){Text("پلاک موتورسیکلت",style=MaterialTheme.typography.labelLarge);CompositionLocalProvider(LocalLayoutDirection provides LayoutDirection.Ltr){Card(shape=RoundedCornerShape(12.dp),colors=CardDefaults.cardColors(containerColor=Color(0xFFF4F4F4))){Row(Modifier.padding(8.dp),verticalAlignment=Alignment.CenterVertically,horizontalArrangement=Arrangement.spacedBy(7.dp)){Box(Modifier.width(30.dp).height(112.dp).background(Color(0xFF17458A),RoundedCornerShape(6.dp)),contentAlignment=Alignment.Center){Text("IR",color=Color.White,fontWeight=FontWeight.Bold)};Column(Modifier.width(160.dp),verticalArrangement=Arrangement.spacedBy(6.dp)){OutlinedTextField(top,{emit(t=Digits.normalize(it).filter(Char::isDigit).take(3))},placeholder={Text("۱۲۳",color=Color.Gray)},singleLine=true,textStyle=LocalTextStyle.current.copy(color=Color.Black),colors=colors,modifier=Modifier.fillMaxWidth().height(52.dp));OutlinedTextField(bottom,{emit(b=Digits.normalize(it).filter(Char::isDigit).take(5))},placeholder={Text("۱۲۳۴۵",color=Color.Gray)},singleLine=true,textStyle=LocalTextStyle.current.copy(color=Color.Black),colors=colors,modifier=Modifier.fillMaxWidth().height(52.dp))}}}};Text("سه رقم در ردیف بالا و پنج رقم در ردیف پایین",style=MaterialTheme.typography.bodySmall,color=MaterialTheme.colorScheme.onSurfaceVariant)}
}
@Composable private fun VehicleEntryPage(vm:AppViewModel,kind:Int,existing:VehicleEntity?=null,onDone:()->Unit,onCancel:()->Unit){val dao=vm.repo.db.civicDao();val vehicles by dao.observeVehicles().collectAsState(initial=emptyList());val people by dao.observePeople().collectAsState(initial=emptyList());val context=LocalContext.current;val scope=rememberCoroutineScope();var title by remember(existing?.id){mutableStateOf(existing?.title.orEmpty())};var plate by remember(existing?.id){mutableStateOf(existing?.plate.orEmpty())};var owner by remember(existing?.id){mutableStateOf(existing?.ownerId)};var ownerName by remember(existing?.id){mutableStateOf(existing?.ownerName.orEmpty())};var customOwner by remember(existing?.id){mutableStateOf(existing?.ownerName?.isNotBlank()==true)};var vehicleType by remember(existing?.id){mutableStateOf(existing?.vehicleType?:"خودرو سواری")};var vehicleId by remember{mutableStateOf(vehicles.firstOrNull()?.id)};var currentKm by remember{mutableStateOf("")};var intervalKm by remember{mutableStateOf("5000")};var oilType by remember{mutableStateOf("")};var note by remember{mutableStateOf("")};var due by remember{mutableStateOf(PersianDate.today().plusMonths(6))};val isVehicle=kind==VEHICLE_ENTRY;val accent=if(isVehicle)Color(0xFF1B8F52) else Color(0xFFD33B45);val vehicleTypes=listOf("خودرو سواری","موتورسیکلت","وانت","کامیون","تریلر","اتوبوس","مینی‌بوس","ماشین‌آلات","سایر");val isMotorcycle=vehicleType=="موتورسیکلت";val motorcycleDigits=Digits.normalize(plate).filter(Char::isDigit);val canonicalPlate=if(isMotorcycle)motorcycleDigits.takeIf{it.length==8}?.let{"موتور${it.take(3)}/${it.drop(3)}"}else ir.kharjyar.app.core.sms.IranianPlateMatcher.canonical(plate)
 Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){TextButton(onCancel){Icon(Icons.Filled.ArrowBack,null);Text("بازگشت به فهرست")};Text(if(isVehicle&&existing!=null)"ویرایش وسیله نقلیه" else if(isVehicle)"ثبت وسیله نقلیه" else "ثبت سرویس و تعویض روغن",style=MaterialTheme.typography.headlineSmall,color=accent);if(isVehicle){
 Text("نوع وسیله نقلیه",style=MaterialTheme.typography.titleMedium,fontWeight=FontWeight.Bold);Row(Modifier.fillMaxWidth().horizontalScroll(rememberScrollState()),horizontalArrangement=Arrangement.spacedBy(6.dp)){vehicleTypes.forEach{type->FilterChip(vehicleType==type,{if(vehicleType!=type){vehicleType=type;plate=""}},{Text(type)})}}
 OutlinedTextField(title,{title=it},label={Text(if(isMotorcycle)"نام یا مدل موتورسیکلت" else "نام یا مدل وسیله نقلیه")},modifier=Modifier.fillMaxWidth())
 if(isMotorcycle)MotorcyclePlateInput(plate,{plate=it})else IranianPlateInput(plate,{plate=it})
 Text(canonicalPlate?.let{"پلاک استاندارد: ${Digits.toPersian(it)}"}?:if(isMotorcycle)"سه رقم بالا و پنج رقم پایین را کامل کنید." else "چهار بخش پلاک را کامل کنید.",color=if(plate.isNotBlank()&&canonicalPlate==null)MaterialTheme.colorScheme.error else MaterialTheme.colorScheme.onSurfaceVariant,style=MaterialTheme.typography.bodySmall)
 Text("مالک",style=MaterialTheme.typography.titleMedium);Row(Modifier.horizontalScroll(rememberScrollState()),horizontalArrangement=Arrangement.spacedBy(6.dp)){FilterChip(owner==null&&!customOwner,{owner=null;customOwner=false;ownerName=""},{Text("خودم")});people.forEach{person->FilterChip(owner==person.id&&!customOwner,{owner=person.id;customOwner=false;ownerName=""},{Text(person.name)})};FilterChip(customOwner,{owner=null;customOwner=true},{Text("شخص دیگر")})}
 if(customOwner)OutlinedTextField(ownerName,{ownerName=it},label={Text("نام مالک (همسر، فرزند یا شخص دیگر)")},singleLine=true,modifier=Modifier.fillMaxWidth())
}else{Text("انتخاب وسیله نقلیه");Row(Modifier.horizontalScroll(rememberScrollState()),horizontalArrangement=Arrangement.spacedBy(6.dp)){vehicles.forEach{v->FilterChip(vehicleId==v.id,{vehicleId=v.id},{Text(v.title)})}};OutlinedTextField(currentKm,{currentKm=Digits.normalize(it).filter(Char::isDigit)},label={Text("کیلومتر فعلی")},modifier=Modifier.fillMaxWidth());OutlinedTextField(intervalKm,{intervalKm=Digits.normalize(it).filter(Char::isDigit)},label={Text("فاصله تعویض بعدی (کیلومتر)")},modifier=Modifier.fillMaxWidth());OutlinedTextField(oilType,{oilType=it},label={Text("نوع یا برند روغن")},modifier=Modifier.fillMaxWidth());OutlinedTextField(note,{note=it},label={Text("توضیحات")},modifier=Modifier.fillMaxWidth());Text("موعد زمانی تعویض بعدی");PersianDateField(due,{due=it})};Button({scope.launch{if(isVehicle){val value=VehicleEntity(id=existing?.id?:0,ownerId=if(customOwner)null else owner,title=title.trim(),plate=canonicalPlate?:return@launch,vehicleType=vehicleType,ownerName=if(customOwner)ownerName.trim()else "");if(existing==null)dao.insertVehicle(value)else dao.updateVehicle(value)}else{val selected=vehicles.firstOrNull{it.id==vehicleId}?:return@launch;val nowKm=currentKm.toIntOrNull()?:0;val nextKm=nowKm+(intervalKm.toIntOrNull()?:5000);val at=due.startOfDayMillis()+9*60*60*1000L;val reminderId=vm.repo.db.reminderDao().insert(ReminderEntity(title="تعویض روغن ${selected.title}",category="تعویض روغن خودرو",note="پلاک ${selected.plate} — موعد کیلومتر ${Digits.toPersian(nextKm.toString())}",nextAt=at));LifeReminderWorker.schedule(context,reminderId,at);dao.insertOilService(VehicleOilServiceEntity(vehicleId=selected.id,servicedAt=System.currentTimeMillis(),currentKm=nowKm,nextKm=nextKm,nextDueAt=at,oilType=oilType.trim(),note=note.trim(),reminderId=reminderId))};showSavedMessage(context,"اطلاعات وسیله نقلیه");onDone()}},enabled=if(isVehicle)title.isNotBlank()&&canonicalPlate!=null&&(!customOwner||ownerName.isNotBlank()) else vehicleId!=null&&currentKm.isNotBlank(),modifier=Modifier.fillMaxWidth(),border=BorderStroke(1.5.dp,accent)){Text(if(isVehicle&&existing!=null)"ذخیره تغییرات" else if(isVehicle)"ثبت وسیله نقلیه" else "ثبت سرویس و فعال‌سازی یادآور")}}
}
